import type { ApiMatch } from "@/types";

export const mockApiMatches: ApiMatch[] = [
  {
    match_id: "1",
    status: "upcoming",
    team_a: "Chameleon",
    team_b: "Cockatoo",
    player_a1: "Alex",
    player_a2: "Sam",
    player_b1: "Jordan",
    player_b2: "Casey",
    scheduled_time: "2025-02-08T10:00:00Z",
    category: "Group A",
    fixture: "Round 1",
  },
  {
    match_id: "2",
    status: "upcoming",
    team_a: "Elephant",
    team_b: "Hedgehog",
    player_a1: "Riley",
    player_a2: "Quinn",
    player_b1: "Morgan",
    player_b2: "Taylor",
    scheduled_time: "2025-02-08T11:30:00Z",
    category: "Group A",
    fixture: "Round 1",
  },
  {
    match_id: "3",
    status: "completed",
    team_a: "Impala",
    team_b: "Jaguar",
    player_a1: "Jamie",
    player_a2: "Robin",
    player_b1: "Drew",
    player_b2: "Sky",
    score_summary: "6-4",
    winner_team: "team_a",
    category: "Group B",
    fixture: "Round 2",
  },
  {
    match_id: "4",
    status: "completed",
    team_a: "Kangaroo",
    team_b: "Rhino",
    player_a1: "Finley",
    player_a2: "Reese",
    player_b1: "Avery",
    player_b2: "Parker",
    score_summary: "3-6",
    winner_team: "team_b",
    category: "Group B",
    fixture: "Round 2",
  },
  {
    match_id: "5",
    status: "upcoming",
    team_a: "Chameleon",
    team_b: "Elephant",
    player_a1: "Parent A",
    player_a2: "Parent B",
    player_b1: "Parent C",
    player_b2: "Parent D",
    scheduled_time: "2025-02-09T09:00:00Z",
    category: "Group A",
    fixture: "Semi-final",
  },
  {
    match_id: "6",
    status: "completed",
    team_a: "Cockatoo",
    team_b: "Hedgehog",
    player_a1: "Alex",
    player_a2: "Sam",
    player_b1: "Morgan",
    player_b2: "Taylor",
    score_summary: "6-2, 6-3",
    winner_team: "team_a",
    category: "Group A",
    fixture: "Round 3",
  },
];
